" Double quote leading a comment line

" file encoding dectection
" http://edyfox.codecarver.org/html/vim_fileencodings_detection.html
" using the following order to test the file's encoding, from strict to loose
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

" set script encoding
scriptencoding = utf-8

" enable pathogen - it's under ~\vimfiles\autoload - ~\vimfiles is already in
" runtimepath, you can check it by :echo &runtimepath in any vim window
" after this, any plugin you want to install can be extracted into a
" subdirectory under ~\vimfiles\bundle, it will be added to rumtimepath 
execute pathogen#infect()

" File type checking, plugin, indent on
filetype plugin indent on

" enable syntax highlight
syntax enable

" install https://github.com/altercation/vim-colors-solarized
" it's said good for eye
if has("gui_running")
	set background=light
else
	set background=dark
endif
colorscheme solarized

" Smart tab
set shiftwidth=4
set tabstop=4
set smarttab

set relativenumber " Show relative number line for quick movement
set number " Show line number

" Install plugin vim-airline
" Always display status line
set laststatus=2

" Backspace works in Insert mode (e.g. not inserting a ^?), but won't delete over line breaks, or automatically-inserted indentation, or the place where insert mode started:
set backspace=indent,eol,start

" GUI font, need to install Ubuntu font if not yet
set guifont=Ubuntu\ Mono:h12

" highlight cursor line
set cursorline

